services:
  nuxt:
    build:
      context: ./nuxt
      dockerfile: Dockerfile.dev
    image: nuxt_image
    container_name: nuxt_container
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./nuxt:/app
      - node_modules:/app/node_modules
    depends_on:
      - laravel
    networks:
      - app-network
    extra_hosts:
      - localhost:host-gateway

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.dev
    image: laravel_image
    container_name: laravel_container
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - app.env
    volumes:
      - ./laravel:/var/www
      - vendor:/var/www/vendor
    command: >
      sh -c 
      "php artisan migrate && 
      php-fpm"
    networks:
      - app-network
    depends_on:
      meilisearch:
        condition: service_started
      db:
        condition: service_healthy
  webserver:
    image: nginx:alpine
    container_name: webserver_container
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www
      - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - laravel

  db:
    image: mysql:8.0
    container_name: db_container
    restart: unless-stopped
    env_file:
      - app.env
    volumes:
      - ./docker-compose/data/mysql:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  meilisearch:
    image: getmeili/meilisearch:v1.13
    container_name: meilisearch_container
    ports:
      - 7700:7700
    env_file:
      - app.env
    volumes:
      - ./docker-compose/data/meilisearch:/meili_data
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  vendor:
